using CCReimagined.Core.Codegen;
using CCReimagined.Core.Model;
using CCReimagined.Core.Providers;

namespace CCReimagined.Core.Tests;

/// <summary>
/// A development aid rather than an assertion: set CCR_DUMP_DIR and run the suite to write one
/// sample class per engine from a fixed schema, which is the quickest way to eyeball what a
/// change to the generator actually did to the output. It does nothing when the variable is unset.
/// </summary>
public sealed class SampleOutputWriter
{
    private static readonly string OutDir =
        Environment.GetEnvironmentVariable("CCR_DUMP_DIR") ?? "";

    [Fact]
    public void WriteOneSamplePerEngine()
    {
        if (OutDir.Length == 0)
            return;

        var schema = new TableSchema
        {
            Table = new TableRef("dbo", "Member"),
            Columns =
            [
                new ColumnInfo { Name = "MemberId", NativeTypeName = "int", ClrType = ClrTypeKind.Int32, IsAutoGenerated = true, IsPrimaryKey = true, Ordinal = 1 },
                new ColumnInfo { Name = "LastName", NativeTypeName = "nvarchar", ClrType = ClrTypeKind.String, MaxLength = 40, Ordinal = 2 },
                new ColumnInfo { Name = "FirstName", NativeTypeName = "nvarchar", ClrType = ClrTypeKind.String, MaxLength = 40, IsNullable = true, Ordinal = 3 },
                new ColumnInfo { Name = "DateOfBirth", NativeTypeName = "date", ClrType = ClrTypeKind.DateOnly, IsNullable = true, Ordinal = 4 },
                new ColumnInfo { Name = "Balance", NativeTypeName = "money", ClrType = ClrTypeKind.Decimal, Ordinal = 5 },
                new ColumnInfo { Name = "IsActive", NativeTypeName = "bit", ClrType = ClrTypeKind.Boolean, Ordinal = 6 },
                new ColumnInfo { Name = "ProgramCode", NativeTypeName = "varchar", ClrType = ClrTypeKind.String, MaxLength = 8, IsNullable = true, Ordinal = 7 },
                new ColumnInfo { Name = "RowVersion", NativeTypeName = "timestamp", ClrType = ClrTypeKind.ByteArray, IsComputed = true, Ordinal = 8 },
            ],
        };

        schema = schema with { KeyColumn = TableSchema.ResolveKeyColumn(schema.Columns, "Member") };

        Directory.CreateDirectory(OutDir);

        foreach (var provider in ProviderRegistry.All)
        {
            var artifact = new CSharpDataClassGenerator().Generate(new GenerationRequest
            {
                Schema = schema,
                Profile = provider.CodegenProfile,
                Namespace = "Contoso.Data",
                ListParameterColumns = ["LastName", "ProgramCode"],
                SourceDescription = "sample schema",
            });

            File.WriteAllText(Path.Combine(OutDir, $"{provider.Id}-{artifact.FileName}"), artifact.Content);
        }
    }
}
