using System.Reflection;
using CCReimagined.Core.Codegen;
using CCReimagined.Core.Model;
using CCReimagined.Core.Providers;
using Microsoft.Data.Sqlite;

namespace CCReimagined.Core.Tests;

/// <summary>
/// The full loop against a real database: create a SQLite file, discover its schema through
/// the provider, generate a data class, compile that class, and drive CRUD through it.
/// SQLite is the engine that can be exercised without a server, so it carries the
/// end-to-end coverage; the other providers share every line of the generator.
/// </summary>
public sealed class SqliteEndToEndTests : IAsyncLifetime
{
    private readonly string _dbPath = Path.Combine(Path.GetTempPath(), $"ccr-{Guid.NewGuid():N}.db");
    private string _connectionString = "";

    public async Task InitializeAsync()
    {
        _connectionString = new SqliteConnectionStringBuilder
        {
            DataSource = _dbPath,
            Mode = SqliteOpenMode.ReadWriteCreate,
        }.ConnectionString;

        await using var cn = new SqliteConnection(_connectionString);
        await cn.OpenAsync();
        await using var cmd = cn.CreateCommand();
        cmd.CommandText = """
            CREATE TABLE Member (
                MemberId     INTEGER PRIMARY KEY,
                LastName     VARCHAR(40) NOT NULL,
                FirstName    VARCHAR(40),
                DateOfBirth  DATETIME,
                Balance      DECIMAL(12,2) NOT NULL DEFAULT 0,
                IsActive     BOOLEAN NOT NULL DEFAULT 1,
                Photo        BLOB,
                ProgramCode  VARCHAR(8)
            );

            CREATE VIEW ActiveMember AS SELECT * FROM Member WHERE IsActive = 1;
            """;
        await cmd.ExecuteNonQueryAsync();
    }

    public Task DisposeAsync()
    {
        SqliteConnection.ClearAllPools();

        if (File.Exists(_dbPath))
            File.Delete(_dbPath);

        return Task.CompletedTask;
    }

    [Fact]
    public async Task Provider_lists_tables_and_views()
    {
        var provider = new SqliteProvider();

        var relations = await provider.ListRelationsAsync(_connectionString);

        Assert.Contains(relations, r => r.Name == "Member" && r.Kind == RelationKind.Table);
        Assert.Contains(relations, r => r.Name == "ActiveMember" && r.Kind == RelationKind.View);
    }

    [Fact]
    public async Task Provider_maps_declared_types_and_finds_the_rowid_key()
    {
        var provider = new SqliteProvider();
        var schema = await provider.GetTableSchemaAsync(_connectionString, new TableRef(null, "Member"));

        var byName = schema.Columns.ToDictionary(c => c.Name, StringComparer.Ordinal);

        Assert.Equal(ClrTypeKind.Int64, byName["MemberId"].ClrType);
        Assert.Equal(ClrTypeKind.String, byName["LastName"].ClrType);
        Assert.Equal(ClrTypeKind.DateTime, byName["DateOfBirth"].ClrType);
        Assert.Equal(ClrTypeKind.Decimal, byName["Balance"].ClrType);
        Assert.Equal(ClrTypeKind.Boolean, byName["IsActive"].ClrType);
        Assert.Equal(ClrTypeKind.ByteArray, byName["Photo"].ClrType);

        Assert.Equal(40, byName["LastName"].MaxLength);
        Assert.False(byName["LastName"].IsNullable);
        Assert.True(byName["FirstName"].IsNullable);

        // INTEGER PRIMARY KEY aliases the rowid, so it auto-numbers.
        Assert.True(byName["MemberId"].IsAutoGenerated);
        Assert.Equal("MemberId", schema.KeyColumn?.Name);
        Assert.True(schema.HasGeneratedKey);
    }

    [Fact]
    public async Task Generated_class_compiles_and_performs_crud_against_sqlite()
    {
        var provider = new SqliteProvider();
        var schema = await provider.GetTableSchemaAsync(_connectionString, new TableRef(null, "Member"));

        var artifact = new CSharpDataClassGenerator().Generate(new GenerationRequest
        {
            Schema = schema,
            Profile = provider.CodegenProfile,
            Namespace = "Generated.Data",
            ClassName = "Member",
            ListParameterColumns = ["LastName", "ProgramCode"],
            SourceDescription = "sqlite test fixture",
        });

        var (assembly, errors) = GeneratedCodeCompiler.Compile(
            artifact.Content,
            "GeneratedMemberSqlite",
            typeof(SqliteConnection));

        Assert.True(assembly is not null, "Generated code did not compile:\n" + string.Join("\n", errors));

        var type = assembly!.GetType("Generated.Data.Member")!;
        var instance = Activator.CreateInstance(type, _connectionString)!;

        Set(instance, "LastName", "Watson");
        Set(instance, "FirstName", "Leigh");
        Set(instance, "Balance", 125.50m);
        Set(instance, "IsActive", true);
        Set(instance, "ProgramCode", "ALPHA");

        await Invoke<object?>(instance, "AddAsync");

        // The INSERT must have brought the generated rowid back.
        var newId = (long)Get(instance, "MemberId")!;
        Assert.True(newId > 0);

        Set(instance, "Balance", 999.99m);
        var updated = await Invoke<int>(instance, "UpdateAsync");
        Assert.Equal(1, updated);

        var reloaded = Activator.CreateInstance(type, _connectionString)!;
        var found = await Invoke<bool>(reloaded, "ReadAsync", newId);
        Assert.True(found);
        Assert.Equal("Watson", Get(reloaded, "LastName"));
        Assert.Equal(999.99m, Get(reloaded, "Balance"));
        Assert.Equal(true, Get(reloaded, "IsActive"));

        Assert.True(await Invoke<bool>(reloaded, "RecExistsAsync", newId));

        // The list getters keyed on the columns the user picked.
        var byLastName = await InvokeStaticList(type, "GetListByLastNameAsync", _connectionString, "Watson");
        Assert.Single(byLastName);

        var byProgram = await InvokeStaticList(type, "GetListByProgramCodeAsync", _connectionString, "ALPHA");
        Assert.Single(byProgram);

        var byMissingProgram = await InvokeStaticList(type, "GetListByProgramCodeAsync", _connectionString, "NOPE");
        Assert.Empty(byMissingProgram);

        var all = await InvokeStaticList(type, "GetAllAsync", _connectionString);
        Assert.Single(all);

        var deleted = await Invoke<int>(reloaded, "DeleteAsync");
        Assert.Equal(1, deleted);
        Assert.False(await Invoke<bool>(reloaded, "RecExistsAsync", newId));
        Assert.False(await Invoke<bool>(reloaded, "ReadAsync", newId));
    }

    [Fact]
    public async Task Nullable_columns_round_trip_as_null()
    {
        var provider = new SqliteProvider();
        var schema = await provider.GetTableSchemaAsync(_connectionString, new TableRef(null, "Member"));

        var artifact = new CSharpDataClassGenerator().Generate(new GenerationRequest
        {
            Schema = schema,
            Profile = provider.CodegenProfile,
            ClassName = "Member",
            ListParameterColumns = ["LastName"],
        });

        var (assembly, errors) = GeneratedCodeCompiler.Compile(
            artifact.Content,
            "GeneratedMemberNulls",
            typeof(SqliteConnection));

        Assert.True(assembly is not null, string.Join("\n", errors));

        var type = assembly!.GetType("Generated.Data.Member")!;
        var instance = Activator.CreateInstance(type, _connectionString)!;

        Set(instance, "LastName", "NullCity");
        // FirstName, DateOfBirth, Photo and ProgramCode all left null.
        await Invoke<object?>(instance, "AddAsync");

        var id = (long)Get(instance, "MemberId")!;
        var reloaded = Activator.CreateInstance(type, _connectionString)!;
        Assert.True(await Invoke<bool>(reloaded, "ReadAsync", id));

        Assert.Null(Get(reloaded, "FirstName"));
        Assert.Null(Get(reloaded, "DateOfBirth"));
        Assert.Null(Get(reloaded, "Photo"));
        Assert.Null(Get(reloaded, "ProgramCode"));
        Assert.Equal("NullCity", Get(reloaded, "LastName"));
    }

    [Fact]
    public async Task Generating_for_a_view_warns_about_the_mutating_methods()
    {
        var provider = new SqliteProvider();
        var schema = await provider.GetTableSchemaAsync(
            _connectionString,
            new TableRef(null, "ActiveMember", RelationKind.View));

        var artifact = new CSharpDataClassGenerator().Generate(new GenerationRequest
        {
            Schema = schema,
            Profile = provider.CodegenProfile,
        });

        Assert.Contains(artifact.Warnings, msg => msg.Contains("view", StringComparison.OrdinalIgnoreCase));

        var (assembly, errors) = GeneratedCodeCompiler.Compile(
            artifact.Content,
            "GeneratedActiveMemberView",
            typeof(SqliteConnection));

        Assert.True(assembly is not null, string.Join("\n", errors));
    }

    // ------------------------------------------------------------------ reflection helpers

    private static void Set(object instance, string property, object? value) =>
        instance.GetType().GetProperty(property)!.SetValue(instance, value);

    private static object? Get(object instance, string property) =>
        instance.GetType().GetProperty(property)!.GetValue(instance);

    private static async Task<T> Invoke<T>(object instance, string method, params object?[] args)
    {
        var info = instance.GetType()
            .GetMethods(BindingFlags.Public | BindingFlags.Instance)
            .First(m => m.Name == method && m.GetParameters().Length == args.Length + 1);

        var full = args.Append((object?)CancellationToken.None).ToArray();
        var task = info.Invoke(instance, full)!;
        await (Task)task;

        var resultProperty = task.GetType().GetProperty("Result");
        return resultProperty is null ? default! : (T)resultProperty.GetValue(task)!;
    }

    private static async Task<System.Collections.IList> InvokeStaticList(
        Type type,
        string method,
        params object?[] args)
    {
        var info = type
            .GetMethods(BindingFlags.Public | BindingFlags.Static)
            .First(m => m.Name == method && m.GetParameters().Length == args.Length + 1);

        var full = args.Append((object?)CancellationToken.None).ToArray();
        var task = (Task)info.Invoke(null, full)!;
        await task;

        return (System.Collections.IList)task.GetType().GetProperty("Result")!.GetValue(task)!;
    }
}
