-- Sample schema for CCReimagined, SQL Server flavour.
-- Mirrors the PostgreSQL and MySQL seeds, plus the types only SQL Server has.

IF DB_ID('ccrsample') IS NULL
    CREATE DATABASE ccrsample;
GO

USE ccrsample;
GO

IF OBJECT_ID('dbo.active_member', 'V')    IS NOT NULL DROP VIEW  dbo.active_member;
IF OBJECT_ID('dbo.member_program', 'U')   IS NOT NULL DROP TABLE dbo.member_program;
IF OBJECT_ID('dbo.claim', 'U')            IS NOT NULL DROP TABLE dbo.claim;
IF OBJECT_ID('dbo.inventory', 'U')        IS NOT NULL DROP TABLE dbo.inventory;
IF OBJECT_ID('dbo.awkward_names', 'U')    IS NOT NULL DROP TABLE dbo.awkward_names;
IF OBJECT_ID('dbo.legacy_lookup', 'U')    IS NOT NULL DROP TABLE dbo.legacy_lookup;
IF OBJECT_ID('dbo.type_zoo', 'U')         IS NOT NULL DROP TABLE dbo.type_zoo;
IF OBJECT_ID('dbo.member', 'U')           IS NOT NULL DROP TABLE dbo.member;
GO

CREATE TABLE dbo.member (
    member_id     int IDENTITY(1,1) PRIMARY KEY,
    last_name     nvarchar(40)  NOT NULL,
    first_name    nvarchar(40)  NULL,
    date_of_birth date          NULL,
    joined_at     datetimeoffset NOT NULL CONSTRAINT df_member_joined DEFAULT SYSDATETIMEOFFSET(),
    balance       money         NOT NULL CONSTRAINT df_member_balance DEFAULT 0,
    is_active     bit           NOT NULL CONSTRAINT df_member_active  DEFAULT 1,
    program_code  varchar(8)    NULL,
    notes         nvarchar(max) NULL,
    photo         varbinary(max) NULL,
    external_ref  uniqueidentifier NULL,
    -- rowversion is generated by the engine and must never appear in INSERT or UPDATE.
    row_version   rowversion
);
GO

CREATE TABLE dbo.claim (
    claim_id  int IDENTITY(1,1) PRIMARY KEY,
    member_id int NOT NULL REFERENCES dbo.member(member_id),
    amount    decimal(10,2) NOT NULL,
    paid_on   date NULL,
    memo      nvarchar(200) NULL
);
GO

-- No IDENTITY: the tool has to guess a key and say so.
CREATE TABLE dbo.legacy_lookup (
    lookup_code varchar(10)  NOT NULL PRIMARY KEY,
    description nvarchar(100) NOT NULL,
    sort_order  smallint NULL
);
GO

CREATE TABLE dbo.member_program (
    member_id    int NOT NULL REFERENCES dbo.member(member_id),
    program_code varchar(8) NOT NULL,
    enrolled_on  date NOT NULL,
    CONSTRAINT pk_member_program PRIMARY KEY (member_id, program_code)
);
GO

CREATE TABLE dbo.awkward_names (
    id                 int IDENTITY(1,1) PRIMARY KEY,
    [int]              int NULL,
    [class]            nvarchar(20) NULL,
    [Unit Cost]        decimal(10,2) NULL,
    [ConnectionString] nvarchar(50) NULL,
    [INTERVIEWER]      nvarchar(40) NULL,
    [2nd_address]      nvarchar(60) NULL
);
GO

CREATE TABLE dbo.inventory (
    inventory_id int IDENTITY(1,1) PRIMARY KEY,
    sku          varchar(24) NOT NULL,
    quantity     int NOT NULL CONSTRAINT df_inv_qty  DEFAULT 0,
    unit_cost    decimal(10,2) NOT NULL CONSTRAINT df_inv_cost DEFAULT 0,
    -- A computed column: readable, never writable.
    total_value  AS (quantity * unit_cost) PERSISTED
);
GO

CREATE TABLE dbo.type_zoo (
    id               int IDENTITY(1,1) PRIMARY KEY,
    c_bit            bit NULL,
    c_tinyint        tinyint NULL,
    c_smallint       smallint NULL,
    c_int            int NULL,
    c_bigint         bigint NULL,
    c_real           real NULL,
    c_float          float NULL,
    c_decimal        decimal(18,4) NULL,
    c_numeric        numeric(10,3) NULL,
    c_money          money NULL,
    c_smallmoney     smallmoney NULL,
    c_char           char(10) NULL,
    c_nchar          nchar(10) NULL,
    c_varchar        varchar(50) NULL,
    c_nvarchar       nvarchar(50) NULL,
    c_varchar_max    varchar(max) NULL,
    c_nvarchar_max   nvarchar(max) NULL,
    c_text           text NULL,
    c_xml            xml NULL,
    c_date           date NULL,
    c_time           time NULL,
    c_datetime       datetime NULL,
    c_datetime2      datetime2 NULL,
    c_smalldatetime  smalldatetime NULL,
    c_datetimeoffset datetimeoffset NULL,
    c_uniqueid       uniqueidentifier NULL,
    c_binary         binary(16) NULL,
    c_varbinary      varbinary(255) NULL,
    c_varbinary_max  varbinary(max) NULL
);
GO

CREATE VIEW dbo.active_member AS
    SELECT member_id, last_name, first_name, balance, program_code
    FROM dbo.member
    WHERE is_active = 1;
GO

INSERT INTO dbo.member (last_name, first_name, date_of_birth, balance, is_active, program_code, notes)
VALUES ('Watson',  'Leigh', '1979-04-12', 125.50, 1, 'ALPHA', 'Seed row.'),
       ('Okonkwo', 'Ada',   '1988-11-02', 0.00,   1, 'BETA',  NULL),
       ('Vasquez', NULL,     NULL,       -42.75,  0, NULL,    NULL);

INSERT INTO dbo.claim (member_id, amount, paid_on, memo)
VALUES (1, 60.00, '2026-01-15', 'Initial claim'),
       (1, 65.50, NULL,          NULL),
       (2, 12.25, '2026-02-01', 'Partial');

INSERT INTO dbo.legacy_lookup (lookup_code, description, sort_order)
VALUES ('ALPHA', 'Alpha program', 1),
       ('BETA',  'Beta program',  2);

INSERT INTO dbo.member_program (member_id, program_code, enrolled_on)
VALUES (1, 'ALPHA', '2025-06-01'),
       (2, 'BETA',  '2025-09-15');

INSERT INTO dbo.inventory (sku, quantity, unit_cost)
VALUES ('SKU-001', 10, 4.25),
       ('SKU-002',  3, 19.99);
GO

PRINT 'ccrsample seeded.';
GO
