using System.Collections.Generic;
using CCReimagined.Core.Model;
using CommunityToolkit.Mvvm.ComponentModel;

namespace CCReimagined.App.Models;

/// <summary>
/// One row of the column grid: the discovered column plus the two choices the user makes
/// about it — whether it is the key, and whether it becomes a list-getter parameter.
///
/// The original tool asked for those in modal dialogs that appeared mid-generation. Here
/// they are just columns in the grid, visible and changeable before anything is generated.
/// </summary>
public sealed partial class ColumnRow : ObservableObject
{
    public ColumnRow(ColumnInfo column) => Column = column;

    public ColumnInfo Column { get; }

    public string Name => Column.Name;

    public string TypeDisplay
    {
        get
        {
            // SQLite reports the type exactly as the column was declared, parentheses and all,
            // so appending the length again would render "VARCHAR(40)(40)".
            if (Column.NativeTypeName.Contains('('))
                return Column.NativeTypeName;

            return Column.MaxLength switch
            {
                -1 => $"{Column.NativeTypeName}(max)",
                > 0 when Column.ClrType is ClrTypeKind.String or ClrTypeKind.ByteArray =>
                    $"{Column.NativeTypeName}({Column.MaxLength})",
                _ => Column.Precision is > 0 && Column.Scale is > 0
                    ? $"{Column.NativeTypeName}({Column.Precision},{Column.Scale})"
                    : Column.NativeTypeName,
            };
        }
    }

    public string ClrTypeDisplay => Column.ClrType == ClrTypeKind.Unknown
        ? "(unmapped)"
        : Column.ClrType.CSharpName() + (Column.IsNullable ? "?" : "");

    public bool IsNullable => Column.IsNullable;

    public bool IsAutoGenerated => Column.IsAutoGenerated;

    public bool IsPrimaryKey => Column.IsPrimaryKey;

    public bool IsComputed => Column.IsComputed;

    /// <summary>Set when this column is the one Read/Update/Delete key on.</summary>
    [ObservableProperty]
    public partial bool IsKey { get; set; }

    /// <summary>Set when the user wants a GetListBy… method taking this column.</summary>
    [ObservableProperty]
    public partial bool IsListParameter { get; set; }

    /// <summary>Short note explaining anything unusual about the column.</summary>
    public string Notes
    {
        get
        {
            var notes = new List<string>();

            if (Column.IsAutoGenerated)
                notes.Add("auto");

            if (Column.IsComputed)
                notes.Add("computed");

            if (Column.IsPrimaryKey)
                notes.Add("pk");

            if (Column.ClrType == ClrTypeKind.Unknown)
                notes.Add("type not mapped — omitted from generation");

            return string.Join(", ", notes);
        }
    }
}
