namespace CCReimagined.Core.Model;

/// <summary>
/// One column of a table or view, as discovered from the live catalog.
/// This is the modern replacement for the old tool's <c>Field</c> class: the same
/// facts, but with the engine's native type name kept alongside a neutral
/// <see cref="ClrTypeKind"/> so generation can target any provider.
/// </summary>
public sealed record ColumnInfo
{
    /// <summary>Column name exactly as the database spells it.</summary>
    public required string Name { get; init; }

    /// <summary>1-based position in the table, as reported by the catalog.</summary>
    public int Ordinal { get; init; }

    /// <summary>The engine's own type name, e.g. "nvarchar", "numeric", "TEXT".</summary>
    public required string NativeTypeName { get; init; }

    /// <summary>Provider-neutral CLR shape, resolved by the provider during discovery.</summary>
    public ClrTypeKind ClrType { get; init; } = ClrTypeKind.Unknown;

    /// <summary>
    /// Maximum character/byte length for variable-length types. <c>-1</c> means
    /// unbounded (varchar(max), text, bytea); <c>null</c> means not applicable.
    /// </summary>
    public int? MaxLength { get; init; }

    public int? Precision { get; init; }

    public int? Scale { get; init; }

    public bool IsNullable { get; init; }

    /// <summary>
    /// True when the database supplies the value on insert (IDENTITY, SERIAL,
    /// AUTO_INCREMENT, INTEGER PRIMARY KEY, GENERATED AS IDENTITY). The old tool
    /// called this the AUTONUMBER field and refused to generate without one.
    /// </summary>
    public bool IsAutoGenerated { get; init; }

    /// <summary>True for computed/generated columns, which must be left out of INSERT and UPDATE.</summary>
    public bool IsComputed { get; init; }

    public bool IsPrimaryKey { get; init; }

    public string? DefaultExpression { get; init; }

    /// <summary>True when neither an INSERT nor an UPDATE may write this column.</summary>
    public bool IsWritable => !IsAutoGenerated && !IsComputed && ClrType != ClrTypeKind.Unknown;

    /// <summary>Length-bounded string columns get a truncating setter in the generated class.</summary>
    public bool HasBoundedLength => ClrType == ClrTypeKind.String && MaxLength is > 0;

    public override string ToString() => $"{Name} {NativeTypeName}{(IsNullable ? " NULL" : " NOT NULL")}";
}
