namespace CCReimagined.Core.Model;

public enum RelationKind
{
    Table,
    View,
}

/// <summary>A schema-qualified reference to a table or view, before its columns are read.</summary>
public sealed record TableRef(string? Schema, string Name, RelationKind Kind = RelationKind.Table)
{
    /// <summary>Display form used in the picker and as the default class-name seed.</summary>
    public string QualifiedName => string.IsNullOrEmpty(Schema) ? Name : $"{Schema}.{Name}";

    public override string ToString() => QualifiedName;
}

/// <summary>A table or view together with the columns discovered for it.</summary>
public sealed record TableSchema
{
    public required TableRef Table { get; init; }

    public required IReadOnlyList<ColumnInfo> Columns { get; init; }

    /// <summary>
    /// The column the generated Read/Update/Delete methods key on. Resolved by
    /// <see cref="ResolveKeyColumn"/> unless the user overrides it in the UI.
    /// </summary>
    public ColumnInfo? KeyColumn { get; init; }

    /// <summary>
    /// For a view, whether the engine will accept writes through it. Always
    /// <see cref="ViewMutability.NotApplicable"/> for a table.
    /// </summary>
    public ViewMutability Mutability { get; init; } = ViewMutability.NotApplicable;

    /// <summary>True when this is a view the engine has confirmed cannot be written through.</summary>
    public bool IsReadOnlyView => Table.Kind == RelationKind.View && Mutability == ViewMutability.ReadOnly;

    /// <summary>
    /// True when <see cref="KeyColumn"/> is genuinely database-generated. When false the
    /// key was guessed, and the UI warns — the same caveat the old tool raised in a
    /// message box, only now it is not fatal to generation.
    /// </summary>
    public bool HasGeneratedKey => KeyColumn?.IsAutoGenerated == true;

    public IEnumerable<ColumnInfo> WritableColumns => Columns.Where(c => c.IsWritable);

    /// <summary>
    /// Picks the key column the way the old tool did, but with more to go on:
    /// an auto-generated column wins, then a single-column primary key, then a
    /// lone integral column named like an id, and only then the first column.
    /// </summary>
    public static ColumnInfo? ResolveKeyColumn(IReadOnlyList<ColumnInfo> columns, string tableName)
    {
        if (columns.Count == 0)
            return null;

        var generated = columns.FirstOrDefault(c => c.IsAutoGenerated);
        if (generated is not null)
            return generated;

        var pk = columns.Where(c => c.IsPrimaryKey).ToList();
        if (pk.Count == 1)
            return pk[0];
        if (pk.Count > 1)
            return pk[0];

        var idish = columns.FirstOrDefault(c =>
            c.ClrType.IsIntegral() &&
            (c.Name.Equals("id", StringComparison.OrdinalIgnoreCase) ||
             c.Name.Equals($"{tableName}id", StringComparison.OrdinalIgnoreCase) ||
             c.Name.EndsWith("id", StringComparison.OrdinalIgnoreCase)));

        return idish ?? columns[0];
    }
}
