using CCReimagined.Core.Model;

namespace CCReimagined.Core.Codegen;

/// <summary>
/// Emits the data-abstraction class that was the whole point of the original tool:
/// properties for every column, plus Read / Add / Update / Delete / RecExists and the
/// list getters keyed on the columns the user chose.
///
/// Unlike the original, nothing here names a concrete ADO.NET type. Every engine-specific
/// decision comes from the <see cref="ICodegenProfile"/> on the request, so the same
/// generator produces SqlClient, Npgsql, MySqlConnector or Sqlite code.
/// </summary>
public sealed class CSharpDataClassGenerator
{
    public GeneratedArtifact Generate(GenerationRequest request)
    {
        var schema = request.Schema;
        var profile = request.Profile;
        var options = request.Options;
        var className = request.EffectiveClassName;
        var key = request.EffectiveKeyColumn;
        var warnings = new List<string>();

        var columns = schema.Columns.Where(c => c.ClrType != ClrTypeKind.Unknown).ToList();

        foreach (var skipped in schema.Columns.Where(c => c.ClrType == ClrTypeKind.Unknown))
            warnings.Add($"Column '{skipped.Name}' has unmapped type '{skipped.NativeTypeName}' and was omitted.");

        var writable = columns.Where(c => c.IsWritable).ToList();

        if (key is null)
            warnings.Add("No key column could be resolved; Read, Update, Delete and RecExists were omitted.");
        else if (!key.IsAutoGenerated)
            warnings.Add($"'{key.Name}' is not database-generated; Add will not populate it after insert.");

        // A view only gets Add, Update and Delete when the engine allows it — or cannot say.
        var isView = schema.Table.Kind == RelationKind.View;
        var mutatingAllowed = options.MutatingMethodsForViews
                              ?? (!isView || schema.Mutability.AllowsMutation());

        if (isView)
        {
            var overridden = options.MutatingMethodsForViews is not null;

            warnings.Add(schema.Mutability switch
            {
                ViewMutability.ReadOnly when !mutatingAllowed =>
                    $"'{schema.Table.QualifiedName}' is a read-only view, so Add, Update and Delete were omitted.",
                ViewMutability.ReadOnly =>
                    $"'{schema.Table.QualifiedName}' is a read-only view, but the mutating methods were "
                    + "generated anyway because they were explicitly requested. They will fail at runtime.",
                ViewMutability.Updatable when !mutatingAllowed =>
                    $"'{schema.Table.QualifiedName}' is an updatable view, but the mutating methods were "
                    + "omitted because that was explicitly requested.",
                ViewMutability.Updatable =>
                    $"'{schema.Table.QualifiedName}' is a view the database reports as updatable.",
                _ when !mutatingAllowed =>
                    $"'{schema.Table.QualifiedName}' is a view; the mutating methods were omitted.",
                _ =>
                    $"'{schema.Table.QualifiedName}' is a view and the database cannot say whether it is "
                    + "updatable, so Add, Update and Delete were generated. They will fail at runtime if it is not.",
            });

            if (overridden)
                warnings.Add("The view mutability setting was overridden rather than taken from the database.");
        }

        if (writable.Count == 0)
            warnings.Add("No writable columns were found; Add and Update were omitted.");

        var sql = new SqlBuilder(profile, schema.Table);
        var w = new CodeWriter();
        var ctx = new EmitContext(request, columns, writable, key, sql, profile, options, className)
        {
            EmitMutatingMethods = mutatingAllowed,
        };

        EmitFileHeader(w, ctx);
        EmitUsings(w, ctx);
        EmitNamespace(w, ctx);

        using (w.Open(ClassDeclaration(ctx)))
        {
            EmitSqlConstants(w, ctx);
            EmitBackingFields(w, ctx);
            EmitConstructors(w, ctx);
            EmitConnectionStringProperty(w, ctx);
            EmitProperties(w, ctx);
            EmitInitialize(w, ctx);
            EmitCopyFields(w, ctx);

            if (key is not null)
            {
                EmitRead(w, ctx, key);

                if (options.GenerateReadAsDataTable)
                    EmitReadAsDataTable(w, ctx, key);

                if (options.GenerateRecExists)
                    EmitRecExists(w, ctx, key);
            }

            if (writable.Count > 0 && mutatingAllowed)
                EmitAdd(w, ctx);

            if (writable.Count > 0 && key is not null && mutatingAllowed)
                EmitUpdate(w, ctx, key);

            if (key is not null && mutatingAllowed)
                EmitDelete(w, ctx, key);

            EmitListGetters(w, ctx);
            EmitPrivateHelpers(w, ctx);

            if (options.ImplementINotifyPropertyChanged)
                EmitInpc(w);
        }

        if (!options.FileScopedNamespace)
        {
            w.Outdent();
            w.Line("}");
        }

        return new GeneratedArtifact
        {
            FileName = className + ".cs",
            Content = w.ToString(),
            Warnings = warnings,
            Language = "csharp",
        };
    }

    // ---------------------------------------------------------------- file scaffolding

    private static void EmitFileHeader(CodeWriter w, EmitContext c)
    {
        if (!c.Options.IncludeProvenanceHeader)
            return;

        w.Line("// <auto-generated>");
        w.Line("//     Generated by CCReimagined.");
        w.Line($"//     Source relation : {c.Request.Schema.Table.QualifiedName} ({c.Request.Schema.Table.Kind})");
        w.Line($"//     Target provider : {c.Profile.DisplayName}");
        w.Line($"//     Requires NuGet  : {c.Profile.NuGetPackage}");

        if (!string.IsNullOrWhiteSpace(c.Request.SourceDescription))
            w.Line($"//     Discovered from : {c.Request.SourceDescription}");

        w.Line("//");
        w.Line("//     Edits to this file are lost the next time it is regenerated. Put hand-written");
        w.Line("//     members in a separate file — the class is declared partial for exactly that.");
        w.Line("// </auto-generated>");
        w.Blank();
        w.Line("#nullable " + (c.Options.NullableReferenceTypes ? "enable" : "disable"));
        w.Blank();
    }

    private static void EmitUsings(CodeWriter w, EmitContext c)
    {
        // System namespaces sort ahead of the provider's, which is the convention every
        // .NET style guide and IDE "organize usings" agrees on.
        var comparer = Comparer<string>.Create((a, b) =>
        {
            var aSystem = a == "System" || a.StartsWith("System.", StringComparison.Ordinal);
            var bSystem = b == "System" || b.StartsWith("System.", StringComparison.Ordinal);

            return aSystem == bSystem
                ? string.CompareOrdinal(a, b)
                : aSystem ? -1 : 1;
        });

        var usings = new SortedSet<string>(comparer)
        {
            "System",
            "System.Collections.Generic",
            "System.Data",
            "System.Data.Common",
            "System.Threading",
            "System.Threading.Tasks",
        };

        if (c.Options.ImplementINotifyPropertyChanged)
            usings.Add("System.ComponentModel");

        foreach (var u in c.Profile.Usings)
            usings.Add(u);

        foreach (var u in usings)
            w.Line($"using {u};");

        w.Blank();
    }

    private static void EmitNamespace(CodeWriter w, EmitContext c)
    {
        if (c.Options.FileScopedNamespace)
        {
            w.Line($"namespace {c.Request.Namespace};");
            w.Blank();
        }
        else
        {
            w.Line($"namespace {c.Request.Namespace}");
            w.Line("{");
            w.Indent();
        }
    }

    private static string ClassDeclaration(EmitContext c)
    {
        var modifiers = c.Options.SealedClass ? "public sealed partial class" : "public partial class";
        var bases = c.Options.ImplementINotifyPropertyChanged ? " : INotifyPropertyChanged" : "";
        return $"{modifiers} {c.ClassName}{bases}";
    }

    // ---------------------------------------------------------------- SQL constants

    private static void EmitSqlConstants(CodeWriter w, EmitContext c)
    {
        w.DocComment("The relation this class maps, as the database spells it.");
        w.Line($"public const string TableName = {Naming.ToCSharpLiteral(c.Request.Schema.Table.QualifiedName)};");
        w.Blank();

        if (c.Key is not null)
        {
            w.RawStringLiteral("private const string SelectByKeySql", c.Sql.SelectByKey(c.Columns, c.Key));
            w.Blank();

            if (c.Options.GenerateRecExists)
            {
                w.RawStringLiteral("private const string ExistsByKeySql", c.Sql.SelectCountByKey(c.Key));
                w.Blank();
            }

            if (c.EmitMutatingMethods)
            {
                w.RawStringLiteral("private const string DeleteByKeySql", c.Sql.Delete(c.Key));
                w.Blank();
            }
        }

        if (c.Writable.Count > 0 && c.EmitMutatingMethods)
        {
            w.RawStringLiteral("private const string InsertSql", c.Sql.Insert(c.Writable, c.Key));
            w.Blank();

            if (c.Key is not null)
            {
                w.RawStringLiteral("private const string UpdateSql", c.Sql.Update(c.Writable, c.Key));
                w.Blank();
            }
        }

        if (c.Options.GenerateGetAll)
        {
            w.RawStringLiteral("private const string SelectAllSql", c.Sql.SelectAll(c.Columns, c.Options.ListMaxRows));
            w.Blank();
        }

        foreach (var filter in c.ListFilterColumns)
        {
            var name = $"SelectBy{Naming.ToIdentifier(filter.Name).TrimStart('_')}Sql";
            w.RawStringLiteral($"private const string {name}", c.Sql.SelectByColumn(c.Columns, filter, c.Options.ListMaxRows));
            w.Blank();
        }
    }

    // ---------------------------------------------------------------- state and properties

    private static void EmitBackingFields(CodeWriter w, EmitContext c)
    {
        w.Line("private string _connectionString = \"\";");

        foreach (var col in c.Columns)
            w.Line($"private {c.TypeOf(col)} {c.FieldOf(col)} = {c.DefaultOf(col)};");

        w.Blank();
    }

    private static void EmitConstructors(CodeWriter w, EmitContext c)
    {
        w.DocComment("Creates an unattached instance; set ConnectionString before any database call.");
        using (w.Open($"public {c.ClassName}()"))
            w.Line("Initialize();");

        w.Blank();

        w.DocComment($"Creates an instance bound to a {c.Profile.DisplayName} connection string.");
        using (w.Open($"public {c.ClassName}(string connectionString) : this()"))
            w.Line("_connectionString = connectionString ?? throw new ArgumentNullException(nameof(connectionString));");

        w.Blank();
    }

    private static void EmitConnectionStringProperty(CodeWriter w, EmitContext c)
    {
        w.DocComment("Connection string used by every method on this instance.");
        using (w.Open("public string ConnectionString"))
        {
            w.Line("get => _connectionString;");
            w.Line("set => _connectionString = value ?? \"\";");
        }

        w.Blank();
    }

    private static void EmitProperties(CodeWriter w, EmitContext c)
    {
        foreach (var col in c.Columns)
        {
            var type = c.TypeOf(col);
            var prop = c.PropOf(col);
            var field = c.FieldOf(col);

            var doc = new List<string>
            {
                $"{col.Name} — {col.NativeTypeName}{(col.IsNullable ? ", nullable" : ", not null")}" +
                $"{(col.IsAutoGenerated ? ", database-generated" : "")}" +
                $"{(col.IsComputed ? ", computed" : "")}" +
                $"{(col.IsPrimaryKey ? ", primary key" : "")}.",
            };

            w.DocComment([.. doc]);

            var truncates = c.Options.TruncateOverlongStrings && col.HasBoundedLength;
            var notifies = c.Options.ImplementINotifyPropertyChanged;

            if (!truncates && !notifies)
            {
                // Nothing to do on set, so an auto-property backed by the field keeps it compact.
                using (w.Open($"public {type} {prop}"))
                {
                    w.Line($"get => {field};");
                    w.Line($"set => {field} = value;");
                }

                w.Blank();
                continue;
            }

            using (w.Open($"public {type} {prop}"))
            {
                w.Line($"get => {field};");

                using (w.Open("set"))
                {
                    if (truncates)
                    {
                        w.Line($"// {col.Name} is declared {col.NativeTypeName}({col.MaxLength}); longer values are trimmed rather than");
                        w.Line("// rejected by the database on write.");
                        var nullGuard = col.IsNullable || !c.Options.NullableReferenceTypes
                            ? "value is not null && "
                            : "";
                        w.Line($"{field} = {nullGuard}value.Length > {col.MaxLength} ? value[..{col.MaxLength}] : value;");
                    }
                    else
                    {
                        w.Line($"{field} = value;");
                    }

                    if (notifies)
                        w.Line($"RaisePropertyChanged(nameof({prop.TrimStart('@')}));");
                }
            }

            w.Blank();
        }
    }

    // ---------------------------------------------------------------- Initialize / CopyFields

    private static void EmitInitialize(CodeWriter w, EmitContext c)
    {
        w.DocComment("Resets every mapped column to its default, leaving ConnectionString alone.");
        using (w.Open("public void Initialize()"))
        {
            foreach (var col in c.Columns)
                w.Line($"{c.FieldOf(col)} = {c.DefaultOf(col)};");
        }

        w.Blank();
    }

    private static void EmitCopyFields(CodeWriter w, EmitContext c)
    {
        w.DocComment(
            "Copies the current row of a reader into this instance.",
            "Columns absent from the result set are left untouched, so a partial SELECT is fine.");

        using (w.Open("public void CopyFields(DbDataReader reader)"))
        {
            w.Line("ArgumentNullException.ThrowIfNull(reader);");
            w.Blank();

            using (w.Open("for (var i = 0; i < reader.FieldCount; i++)"))
            {
                // Matching on the upper-cased name makes the copy insensitive to how the
                // engine cases column names, unless the table itself relies on that casing.
                var label = c.CaseInsensitiveLabels ? "reader.GetName(i).ToUpperInvariant()" : "reader.GetName(i)";

                using (w.Open($"switch ({label})"))
                {
                    foreach (var col in c.Columns)
                    {
                        var literal = Naming.ToCSharpLiteral(
                            c.CaseInsensitiveLabels ? col.Name.ToUpperInvariant() : col.Name);

                        w.Line($"case {literal}:");
                        w.Indent();
                        w.Line($"{c.FieldOf(col)} = {c.ReadExpression(col, "reader", "i")};");
                        w.Line("break;");
                        w.Outdent();
                    }
                }
            }
        }

        w.Blank();
    }

    // ---------------------------------------------------------------- CRUD

    private static void EmitRead(CodeWriter w, EmitContext c, ColumnInfo key)
    {
        var keyType = c.NonNullableTypeOf(key);

        w.DocComment(
            $"Loads the row whose {key.Name} matches <paramref name=\"id\"/>.",
            "Returns false and leaves this instance untouched when no such row exists.");

        using (w.Open($"public async Task<bool> ReadAsync({keyType} id, CancellationToken cancellationToken = default)"))
        {
            w.Line("await using var connection = await OpenConnectionAsync(cancellationToken).ConfigureAwait(false);");
            w.Line($"await using var command = new {c.Profile.CommandTypeName}(SelectByKeySql, connection);");
            w.Line(c.BindLine(key, "id"));
            w.Blank();
            w.Line("await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);");
            w.Blank();

            using (w.Open("if (!await reader.ReadAsync(cancellationToken).ConfigureAwait(false))"))
                w.Line("return false;");

            w.Blank();
            w.Line("CopyFields(reader);");
            w.Line("return true;");
        }

        w.Blank();

        if (c.Options.GenerateSyncWrappers)
        {
            w.DocComment($"Blocking wrapper over <see cref=\"ReadAsync\"/>.");
            w.Line($"public bool Read({keyType} id) => ReadAsync(id).GetAwaiter().GetResult();");
            w.Blank();
        }
    }

    private static void EmitReadAsDataTable(CodeWriter w, EmitContext c, ColumnInfo key)
    {
        var keyType = c.NonNullableTypeOf(key);

        w.DocComment(
            $"Returns the row whose {key.Name} matches <paramref name=\"id\"/> as a DataTable.",
            "This is the portable replacement for the original tool's ReadAsDataSet: DataTable.Load",
            "works over any DbDataReader, so no provider-specific DataAdapter is needed.");

        using (w.Open($"public async Task<DataTable> ReadAsDataTableAsync({keyType} id, CancellationToken cancellationToken = default)"))
        {
            w.Line("await using var connection = await OpenConnectionAsync(cancellationToken).ConfigureAwait(false);");
            w.Line($"await using var command = new {c.Profile.CommandTypeName}(SelectByKeySql, connection);");
            w.Line(c.BindLine(key, "id"));
            w.Blank();
            w.Line("await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);");
            w.Line("var table = new DataTable(TableName);");
            w.Line("table.Load(reader);");
            w.Line("return table;");
        }

        w.Blank();

        if (c.Options.GenerateSyncWrappers)
        {
            w.Line($"public DataTable ReadAsDataTable({keyType} id) => ReadAsDataTableAsync(id).GetAwaiter().GetResult();");
            w.Blank();
        }
    }

    private static void EmitRecExists(CodeWriter w, EmitContext c, ColumnInfo key)
    {
        var keyType = c.NonNullableTypeOf(key);

        w.DocComment($"True when a row with the given {key.Name} exists.");

        using (w.Open($"public async Task<bool> RecExistsAsync({keyType} id, CancellationToken cancellationToken = default)"))
        {
            w.Line("await using var connection = await OpenConnectionAsync(cancellationToken).ConfigureAwait(false);");
            w.Line($"await using var command = new {c.Profile.CommandTypeName}(ExistsByKeySql, connection);");
            w.Line(c.BindLine(key, "id"));
            w.Blank();
            w.Line("var scalar = await command.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false);");
            w.Line("return scalar is not null && scalar is not DBNull && Convert.ToInt64(scalar) > 0;");
        }

        w.Blank();

        if (c.Options.GenerateSyncWrappers)
        {
            w.Line($"public bool RecExists({keyType} id) => RecExistsAsync(id).GetAwaiter().GetResult();");
            w.Blank();
        }
    }

    private static void EmitAdd(CodeWriter w, EmitContext c)
    {
        var fetchesKey = c.Key is not null && c.Key.IsAutoGenerated;

        var doc = new List<string> { "Inserts this instance as a new row." };
        if (fetchesKey)
        {
            doc.Add($"The database-generated {c.Key!.Name} is read back into {c.PropOf(c.Key)} on success.");
        }
        else
        {
            doc.Add("No key is read back, because the key column is not database-generated —");
            doc.Add("set it yourself before calling this.");
        }

        w.DocComment([.. doc]);

        using (w.Open("public async Task AddAsync(CancellationToken cancellationToken = default)"))
        {
            w.Line("await using var connection = await OpenConnectionAsync(cancellationToken).ConfigureAwait(false);");
            w.Line($"await using var command = new {c.Profile.CommandTypeName}(InsertSql, connection);");

            foreach (var col in c.Writable)
                w.Line(c.BindLine(col, c.FieldOf(col)));

            w.Blank();

            if (fetchesKey)
            {
                w.Line("var scalar = await command.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false);");
                w.Blank();

                using (w.Open("if (scalar is not null && scalar is not DBNull)"))
                    w.Line($"{c.FieldOf(c.Key!)} = {c.ConvertScalar(c.Key!, "scalar")};");
            }
            else
            {
                w.Line("await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);");
            }
        }

        w.Blank();

        if (c.Options.GenerateSyncWrappers)
        {
            w.Line("public void Add() => AddAsync().GetAwaiter().GetResult();");
            w.Blank();
        }
    }

    private static void EmitUpdate(CodeWriter w, EmitContext c, ColumnInfo key)
    {
        w.DocComment(
            $"Writes every writable column back to the row identified by {key.Name}.",
            "Returns the number of rows affected, which is zero when the key matches nothing.");

        using (w.Open("public async Task<int> UpdateAsync(CancellationToken cancellationToken = default)"))
        {
            w.Line("await using var connection = await OpenConnectionAsync(cancellationToken).ConfigureAwait(false);");
            w.Line($"await using var command = new {c.Profile.CommandTypeName}(UpdateSql, connection);");

            foreach (var col in c.Writable.Where(x => x.Name != key.Name))
                w.Line(c.BindLine(col, c.FieldOf(col)));

            w.Line(c.BindLine(key, c.FieldOf(key)));
            w.Blank();
            w.Line("return await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);");
        }

        w.Blank();

        if (c.Options.GenerateSyncWrappers)
        {
            w.Line("public int Update() => UpdateAsync().GetAwaiter().GetResult();");
            w.Blank();
        }
    }

    private static void EmitDelete(CodeWriter w, EmitContext c, ColumnInfo key)
    {
        w.DocComment(
            $"Deletes the row identified by this instance's {key.Name}.",
            "Returns the number of rows affected.");

        using (w.Open("public async Task<int> DeleteAsync(CancellationToken cancellationToken = default)"))
        {
            w.Line("await using var connection = await OpenConnectionAsync(cancellationToken).ConfigureAwait(false);");
            w.Line($"await using var command = new {c.Profile.CommandTypeName}(DeleteByKeySql, connection);");
            w.Line(c.BindLine(key, c.FieldOf(key)));
            w.Blank();
            w.Line("return await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);");
        }

        w.Blank();

        if (c.Options.GenerateSyncWrappers)
        {
            w.Line("public int Delete() => DeleteAsync().GetAwaiter().GetResult();");
            w.Blank();
        }
    }

    // ---------------------------------------------------------------- list getters

    private static void EmitListGetters(CodeWriter w, EmitContext c)
    {
        if (c.Options.GenerateGetAll)
        {
            w.DocComment(
                $"Reads every row of {c.Request.Schema.Table.QualifiedName}" +
                (c.Options.ListMaxRows > 0 ? $", capped at {c.Options.ListMaxRows} rows." : "."));

            using (w.Open($"public static async Task<List<{c.ClassName}>> GetAllAsync(string connectionString, CancellationToken cancellationToken = default)"))
                w.Line("return await QueryAsync(connectionString, SelectAllSql, static _ => { }, cancellationToken).ConfigureAwait(false);");

            w.Blank();

            if (c.Options.GenerateSyncWrappers)
            {
                w.Line($"public static List<{c.ClassName}> GetAll(string connectionString) =>");
                w.Indent();
                w.Line("GetAllAsync(connectionString).GetAwaiter().GetResult();");
                w.Outdent();
                w.Blank();
            }
        }

        foreach (var filter in c.ListFilterColumns)
        {
            var suffix = Naming.ToIdentifier(filter.Name).TrimStart('_');
            var paramName = char.ToLowerInvariant(suffix[0]) + (suffix.Length > 1 ? suffix[1..] : "");
            if (paramName == "connectionString" || paramName == "cancellationToken")
                paramName += "Value";

            var paramType = c.NonNullableTypeOf(filter);

            w.DocComment(
                $"Reads every row whose {filter.Name} matches <paramref name=\"{paramName}\"/>." +
                (c.Options.ListMaxRows > 0 ? $" Capped at {c.Options.ListMaxRows} rows." : ""));

            using (w.Open($"public static async Task<List<{c.ClassName}>> GetListBy{suffix}Async(string connectionString, {paramType} {paramName}, CancellationToken cancellationToken = default)"))
            {
                w.Line($"return await QueryAsync(connectionString, SelectBy{suffix}Sql, command =>");
                w.Line("{");
                w.Indent();
                w.Line(c.BindLine(filter, paramName));
                w.Outdent();
                w.Line("}, cancellationToken).ConfigureAwait(false);");
            }

            w.Blank();

            if (c.Options.GenerateSyncWrappers)
            {
                w.Line($"public static List<{c.ClassName}> GetListBy{suffix}(string connectionString, {paramType} {paramName}) =>");
                w.Indent();
                w.Line($"GetListBy{suffix}Async(connectionString, {paramName}).GetAwaiter().GetResult();");
                w.Outdent();
                w.Blank();
            }
        }
    }

    // ---------------------------------------------------------------- private helpers

    private static void EmitPrivateHelpers(CodeWriter w, EmitContext c)
    {
        w.DocComment("Opens and returns a connection using this instance's ConnectionString.");
        using (w.Open($"private async Task<{c.Profile.ConnectionTypeName}> OpenConnectionAsync(CancellationToken cancellationToken)"))
        {
            using (w.Open("if (string.IsNullOrWhiteSpace(_connectionString))"))
                w.Line($"throw new InvalidOperationException(\"{c.ClassName}.ConnectionString has not been set.\");");

            w.Blank();
            w.Line($"var connection = new {c.Profile.ConnectionTypeName}(_connectionString);");
            w.Line("await connection.OpenAsync(cancellationToken).ConfigureAwait(false);");
            w.Line("return connection;");
        }

        w.Blank();

        w.DocComment("Runs a list query and materialises one instance per row.");
        using (w.Open($"private static async Task<List<{c.ClassName}>> QueryAsync(string connectionString, string sql, Action<{c.Profile.CommandTypeName}> bind, CancellationToken cancellationToken)"))
        {
            w.Line("ArgumentException.ThrowIfNullOrWhiteSpace(connectionString);");
            w.Blank();
            w.Line($"var results = new List<{c.ClassName}>();");
            w.Blank();
            w.Line($"await using var connection = new {c.Profile.ConnectionTypeName}(connectionString);");
            w.Line("await connection.OpenAsync(cancellationToken).ConfigureAwait(false);");
            w.Blank();
            w.Line($"await using var command = new {c.Profile.CommandTypeName}(sql, connection);");
            w.Line("bind(command);");
            w.Blank();
            w.Line("await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);");
            w.Blank();

            using (w.Open("while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))"))
            {
                w.Line($"var item = new {c.ClassName}(connectionString);");
                w.Line("item.CopyFields(reader);");
                w.Line("results.Add(item);");
            }

            w.Blank();
            w.Line("return results;");
        }

        w.Blank();

        w.DocComment(
            "Adds a typed parameter, mapping a null CLR value onto SQL NULL.",
            "A non-zero size pins the parameter's declared length instead of letting the provider",
            "infer one per call, which keeps the server reusing a single cached plan.",
            $"The DbType members come from {c.Profile.DbTypeEnumName}, so this class is tied to",
            $"{c.Profile.NuGetPackage} — regenerate against another profile to retarget it.");

        using (w.Open($"private static void Bind({c.Profile.CommandTypeName} command, string name, {c.Profile.DbTypeEnumName} type, object? value, int size = 0)"))
        {
            w.Line("var parameter = command.Parameters.Add(name, type);");
            w.Blank();

            using (w.Open("if (size != 0)"))
                w.Line("parameter.Size = size;");

            w.Blank();
            w.Line("parameter.Value = value ?? DBNull.Value;");
        }

        w.Blank();

        if (c.NeedsEmptyStringHelper)
        {
            w.DocComment("Treats an empty string as SQL NULL, matching the original generator's behaviour.");
            w.Line("private static object? NullIfEmpty(string? value) => string.IsNullOrEmpty(value) ? null : value;");
            w.Blank();
        }
    }

    private static void EmitInpc(CodeWriter w)
    {
        w.Line("public event PropertyChangedEventHandler? PropertyChanged;");
        w.Blank();

        using (w.Open("private void RaisePropertyChanged(string propertyName)"))
            w.Line("PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));");

        w.Blank();
    }
}

/// <summary>The result of a generation run: the file to write, plus anything worth telling the user.</summary>
public sealed record GeneratedArtifact
{
    public required string FileName { get; init; }

    public required string Content { get; init; }

    public IReadOnlyList<string> Warnings { get; init; } = [];

    public string Language { get; init; } = "csharp";
}
