using CCReimagined.Core.Model;

namespace CCReimagined.Core.Codegen;

/// <summary>
/// Builds the SQL text embedded in a generated class. Kept apart from the C# emitter so
/// the statements can be asserted on directly in tests, and so adding an engine means
/// supplying a profile rather than editing the generator.
/// </summary>
public sealed class SqlBuilder
{
    private readonly ICodegenProfile _profile;
    private readonly TableRef _table;

    public SqlBuilder(ICodegenProfile profile, TableRef table)
    {
        _profile = profile;
        _table = table;
    }

    private string Relation => _profile.QualifyRelation(_table);

    private string Param(ColumnInfo c) => _profile.ParameterPrefix + Naming.ToParameterName(c.Name);

    private string Col(ColumnInfo c) => _profile.QuoteIdentifier(c.Name);

    /// <summary>Wraps a comma-separated list so no emitted SQL line runs past ~96 characters.</summary>
    private static string WrapList(IEnumerable<string> items, string indent = "    ")
    {
        var lines = new List<string>();
        var current = new System.Text.StringBuilder();

        foreach (var item in items)
        {
            var piece = current.Length == 0 ? item : ", " + item;
            if (current.Length > 0 && current.Length + piece.Length > 92)
            {
                lines.Add(current.ToString());
                current.Clear();
                current.Append(item);
            }
            else
            {
                current.Append(piece);
            }
        }

        if (current.Length > 0)
            lines.Add(current.ToString());

        return string.Join(",\n" + indent, lines.Select(l => l.TrimEnd(',', ' ')));
    }

    public string SelectColumnList(IReadOnlyList<ColumnInfo> columns) =>
        WrapList(columns.Select(Col));

    public string SelectByKey(IReadOnlyList<ColumnInfo> columns, ColumnInfo key) => $"""
        SELECT {SelectColumnList(columns)}
        FROM {Relation}
        WHERE {Col(key)} = {Param(key)}
        """;

    public string SelectCountByKey(ColumnInfo key) => $"""
        SELECT COUNT(*)
        FROM {Relation}
        WHERE {Col(key)} = {Param(key)}
        """;

    public string SelectAll(IReadOnlyList<ColumnInfo> columns, int maxRows)
    {
        var top = maxRows > 0 && _profile.LimitIsPrefix ? _profile.LimitClause(maxRows) + " " : "";
        var tail = maxRows > 0 && !_profile.LimitIsPrefix ? "\n" + _profile.LimitClause(maxRows) : "";

        return $"""
            SELECT {top}{SelectColumnList(columns)}
            FROM {Relation}{tail}
            """;
    }

    public string SelectByColumn(IReadOnlyList<ColumnInfo> columns, ColumnInfo filter, int maxRows)
    {
        var top = maxRows > 0 && _profile.LimitIsPrefix ? _profile.LimitClause(maxRows) + " " : "";
        var tail = maxRows > 0 && !_profile.LimitIsPrefix ? "\n" + _profile.LimitClause(maxRows) : "";

        return $"""
            SELECT {top}{SelectColumnList(columns)}
            FROM {Relation}
            WHERE {Col(filter)} = {Param(filter)}{tail}
            """;
    }

    /// <summary>
    /// An INSERT over the writable columns. When the engine returns generated keys inline
    /// (PostgreSQL) the RETURNING clause is part of this statement; otherwise the scalar
    /// SELECT that fetches the new key is appended as a second statement in the batch.
    /// </summary>
    public string Insert(IReadOnlyList<ColumnInfo> writable, ColumnInfo? key)
    {
        var body = $"""
            INSERT INTO {Relation} (
                {WrapList(writable.Select(Col))}
            )
            VALUES (
                {WrapList(writable.Select(Param))}
            )
            """;

        if (key is null || !key.IsAutoGenerated)
            return body;

        return _profile.IdentityStrategy switch
        {
            // Part of the same statement.
            IdentityStrategy.ReturningClause or IdentityStrategy.ReturningIntoParameter =>
                body + "\n" + _profile.IdentityRetrievalSql(_table, key),

            // A second statement in the same batch.
            IdentityStrategy.AppendedSelect => body + ";\n" + _profile.IdentityRetrievalSql(_table, key),

            _ => body,
        };
    }

    public string Update(IReadOnlyList<ColumnInfo> writable, ColumnInfo key)
    {
        var assignments = writable
            .Where(c => !string.Equals(c.Name, key.Name, StringComparison.Ordinal))
            .Select(c => $"{Col(c)} = {Param(c)}");

        return $"""
            UPDATE {Relation} SET
                {WrapList(assignments, "    ")}
            WHERE {Col(key)} = {Param(key)}
            """;
    }

    public string Delete(ColumnInfo key) => $"""
        DELETE FROM {Relation}
        WHERE {Col(key)} = {Param(key)}
        """;

    public string ParameterName(ColumnInfo c) => Param(c);
}
